### PR TITLE
Fixed #34217 -- Fixed migration crash when removing check constraints on MySQL < 8.0.16.

### PR DESCRIPTION
**Pull request by DevilsAutumn**
[Ticket 34217](https://code.djangoproject.com/ticket/34217)

### CODE REVIEW

**Review by felixxm — COMMENTED** [review]
@DevilsAutumn Thanks :+1: 

I updated an existing test instead of creating a new one.

**Comment by DevilsAutumn** [comment]
> @DevilsAutumn Thanks 👍
> 
> I updated an existing test instead of creating a new one.

okay!!

**Comment by timgraham** [comment]
Should `_create_check_sql()` have the same logic returning `None` if constraints aren't supported? This test which was entirely skipped now crashes at the `set_up_test_model()` step ("SQL compilation error: syntax error line 1 at position 96 unexpected 'CHECK'." on Snowflake. Did I miss some way that it works on MySQL < 8.0.16?

**Comment by felixxm** [comment]
> Did I miss some way that it works on MySQL < 8.0.16?

This is controlled by `DatabaseWrapper.data_type_check_constraints`, so it doesn't reach `_create_check_sql()` on MySQL < 8.0.16.

**Comment by felixxm** [comment]
> Should `_create_check_sql()` have the same logic returning `None` if constraints aren't supported? This test which was entirely skipped now crashes at the `set_up_test_model()` step ("SQL compilation error: syntax error line 1 at position 96 unexpected 'CHECK'." on Snowflake.

Agreed.

> Did I miss some way that it works on MySQL < 8.0.16?

I'm not sure why it works on MySQL < 8.0.16, it seems that MySQL is ignoring `ADD CONSTRAINT...`  statements instead of raising an exception.
