### PR TITLE
Fixed #31190 -- Fixed prefetch_related() crash for GenericForeignKey with custom ContentType foreign key.

### PR DESCRIPTION
**Pull request by HackoDev**
Hello there.

I'm not sure that it's a right way, but when I have generic foreign key like: 

`obj = GenericForeignKey('object_content_type', 'object_id')`

and 

`some_instances = GenericRelation('some_app.SomeModel', object_id_field='object_id', content_type_field='object_content_type')`

When I try to get all `some_instances`, I get the next error:

`AttributeError: 'SomeModel' object has no attribute 'content_type_id'`

### CODE REVIEW

**Comment by felixxm** [comment]
@HackoDev Thanks for this patch :+1: It looks like a regression in dffa3e1992562ba60512d96d1eb5859ffff2ceb5. Can you create [a new ticket](https://code.djangoproject.com/newticket)? Also a regression test is required.

**Comment by HackoDev** [comment]
Sure.

**Comment by felixxm** [comment]
@HackoDev I attached [a regression test](https://code.djangoproject.com/attachment/ticket/31190/test-31190.diff) to the ticket.

**Comment by felixxm** [comment]
@HackoDev Can you add also a release notes (`3.0.3.txt`)?

**Comment by HackoDev** [comment]
no problem, let me do that.

**Comment by HackoDev** [comment]
@felixxm Done

**Comment by felixxm** [comment]
@HackoDev Thanks :+1: Welcome aboard :boat:

**Comment by HackoDev** [comment]
Thank you! 🤝
