### PR TITLE
Fixed #32833 - inlined ContentType.model_class() in ContentTypeManager.get_for_models()

### PR DESCRIPTION
**Pull request by HMaker**
On migrations the versioned content type objects does not implement `ContentType.model_class()`, when `ContentTypeManager.get_for_models()` is called and some content type is not in cache a query is made to load them from DB, if at last one is found then `ContentType.model_class()` is called on loaded objects which causes `AttributeError` to be raised.

Followed suggestions given in [ticket discussion](https://code.djangoproject.com/ticket/32833) and inlined `ContentType.model_class()` logic in `ContentTypeManager.get_for_models()`.

### CODE REVIEW

**Comment by charettes** [comment]
:wave: @HMaker! You'll want to branch of the `main` branch and target it in your PR as well. Mergers will take care of the backports if necessary.

**Comment by HMaker** [comment]
>  @HMaker! You'll want to branch of the `main` branch and target it in your PR as well. Mergers will take care of the backports if necessary.

I found that bug when working on 3.1 branch so I based patch from there.

**Comment by charettes** [comment]
@HMaker I understand but your patch will likely not be backported to 3.1 or 3.2 as it's not a regression (the bug has been around for a longer time). Even if it was it would be first merged in the `main` branch and then cherry-picked from there.

**Comment by HMaker** [comment]
I should rebase my commits onto main branch?

**Comment by charettes** [comment]
@HMaker yes if possible, otherwise mergers can deal with it as well.

**Comment by HMaker** [comment]
@charettes ok rebased it and the patch works on main branch. What should be done now? need to wait checks finish?

**Comment by charettes** [comment]
@HMaker yep and uncheck _patch needs improvement_ checkbox in ticket-32833. You should eventually get a review as the _review queue_ is based of `has_patch AND NOT needs_improvements`.

Thanks a lot for working on a patch 🙇 ❤️

File: tests/contenttypes_tests/test_operations.py [hunk 1]
```diff
@@ -74,9 +74,36 @@ def test_missing_content_type_rename_ignore(self):
...
         self.assertTrue(ContentType.objects.filter(app_label='contenttypes_tests', model='renamedfoo').exists())
         call_command('migrate', 'contenttypes_tests', 'zero', database='default', interactive=False, verbosity=0)
         self.assertTrue(ContentType.objects.filter(app_label='contenttypes_tests', model='foo').exists())
         self.assertTrue(ContentType.objects.filter(app_label='contenttypes_tests', model='renamedfoo').exists())
+
+
+@override_settings(
+    MIGRATION_MODULES=dict(
+        settings.MIGRATION_MODULES,
+        contenttypes_tests='contenttypes_tests.operations_migrations',
```
Comment (felixxm) [inline tests/contenttypes_tests/test_operations.py:88]: I would use separate set of migrations. You create a new folder, e.g. `tests/contenttypes_tests/operations_migrations_multiple_models/`.

File: tests/contenttypes_tests/test_operations.py [hunk 2]
```diff
@@ -74,9 +74,36 @@ def test_missing_content_type_rename_ignore(self):
...
+    ),
+)
+class ContentTypeManagerOperationsTests(TransactionTestCase):
+    databases = {'default', 'other'}
```
Comment (felixxm) [inline tests/contenttypes_tests/test_operations.py:92]: We don't test migrations on `other` so this line can be removed.
```suggestion
```

File: tests/contenttypes_tests/test_operations.py [hunk 3]
```diff
@@ -74,9 +74,36 @@ def test_missing_content_type_rename_ignore(self):
...
         self.assertTrue(ContentType.objects.filter(app_label='contenttypes_tests', model='foo').exists())
         self.assertTrue(ContentType.objects.filter(app_label='contenttypes_tests', model='renamedfoo').exists())
+
+
+@override_settings(
+    MIGRATION_MODULES=dict(
+        settings.MIGRATION_MODULES,
+        contenttypes_tests='contenttypes_tests.operations_migrations',
+    ),
+)
```
Comment (felixxm) [inline tests/contenttypes_tests/test_operations.py:90]:
```suggestion
@override_settings(MIGRATION_MODULES={
    **settings.MIGRATION_MODULES,
    'contenttypes_tests': 'contenttypes_tests.operations_migrations',
})
```

File: tests/contenttypes_tests/test_operations.py [hunk 4]
```diff
@@ -74,9 +74,36 @@ def test_missing_content_type_rename_ignore(self):
...
+class ContentTypeManagerOperationsTests(TransactionTestCase):
+    databases = {'default', 'other'}
+    available_apps = [
+        'contenttypes_tests',
+        'django.contrib.contenttypes',
+    ]
+
+    def setUp(self) -> None:
```
Comment (felixxm) [inline tests/contenttypes_tests/test_operations.py:98]: Please remove type annotations. We don't currently use them in Django.

File: tests/contenttypes_tests/test_operations.py [hunk 5]
```diff
@@ -74,9 +74,36 @@ def test_missing_content_type_rename_ignore(self):
...
+        call_command('migrate', 'contenttypes_tests', 'zero', database='default', interactive=False, verbosity=0)
```
Comment (felixxm) [inline tests/contenttypes_tests/test_operations.py:99]: To avoid isolation issue you should rather revert migrations in tests, e.g.
```python
    def test_get_for_models_creation_on_migration(self):
        call_command('migrate', 'contenttypes_tests', '0003', database='default', interactive=False, verbosity=0)
        try:
            assertions ....
        finally:
            call_command('migrate', 'contenttypes_tests', 'zero', database='default', interactive=False, verbosity=0
```

File: tests/contenttypes_tests/test_operations.py [hunk 6]
```diff
@@ -74,9 +74,36 @@ def test_missing_content_type_rename_ignore(self):
...
+
+    def test_get_for_models_creation_on_migration(self):
+        ContentType.objects.clear_cache()
```
Comment (felixxm) [inline tests/contenttypes_tests/test_operations.py:102]: Is this necessary?

File: tests/contenttypes_tests/operations_migrations/0001_initial.py [hunk 7]
```diff
@@ -10,4 +10,16 @@ class Migration(migrations.Migration):
...
+            [
+                ('id', models.AutoField(primary_key=True)),
+            ],
+        ),
+        migrations.CreateModel(
+            'Baz',
+            [
+                ('id', models.AutoField(primary_key=True)),
+            ],
+        ),
```
Comment (felixxm) [inline tests/contenttypes_tests/operations_migrations/0001_initial.py:24]: Do we need three models? two should be enough.

File: tests/contenttypes_tests/test_operations.py [hunk 8]
```diff
@@ -74,9 +74,36 @@ def test_missing_content_type_rename_ignore(self):
...
+        call_command('migrate', 'contenttypes_tests', '0003', database='default', interactive=False, verbosity=0)
+
+    def test_get_for_models_load_on_migration(self):
+        ContentType.objects.create(app_label='contenttypes_tests', model='foo')
+        ContentType.objects.create(app_label='contenttypes_tests', model='baz')
+        ContentType.objects.clear_cache()
```
Comment (felixxm) [inline tests/contenttypes_tests/test_operations.py:108]: Is this necessary?

File: tests/contenttypes_tests/test_operations.py [hunk 9]
```diff
@@ -74,9 +74,36 @@ def test_missing_content_type_rename_ignore(self):
...
+        call_command('migrate', 'contenttypes_tests', '0003', database='default', interactive=False, verbosity=0)
```
Comment (felixxm) [inline tests/contenttypes_tests/test_operations.py:109]: Can we check that `get_for_models()` works properly in migrations, not only confirm that it doesn't crash?

File: tests/contenttypes_tests/test_operations.py [hunk 10]
```diff
@@ -74,9 +74,36 @@ def test_missing_content_type_rename_ignore(self):
...
+    databases = {'default', 'other'}
+    available_apps = [
+        'contenttypes_tests',
+        'django.contrib.contenttypes',
+    ]
+
+    def setUp(self) -> None:
+        call_command('migrate', 'contenttypes_tests', 'zero', database='default', interactive=False, verbosity=0)
+
+    def test_get_for_models_creation_on_migration(self):
```
Comment (felixxm) [inline tests/contenttypes_tests/test_operations.py:101]: This test works without a patch.

**Review by felixxm — COMMENTED** [review]
@HMaker Thanks for this patch :+1: I left comments.

**Comment by charettes** [comment]
FWIW you don't even need migrations to reproduce the problem.

Creating a `ProjectState` instance with a `ContentType` model should do

```diff
diff --git a/tests/contenttypes_tests/test_models.py b/tests/contenttypes_tests/test_models.py
index 0554d13184..50f4016b56 100644
--- a/tests/contenttypes_tests/test_models.py
+++ b/tests/contenttypes_tests/test_models.py
@@ -1,5 +1,7 @@
+from django.apps import apps
 from django.contrib.contenttypes.models import ContentType, ContentTypeManager
 from django.db import models
+from django.db.migrations.state import ProjectState
 from django.test import TestCase, override_settings
 from django.test.utils import isolate_apps

@@ -78,6 +80,11 @@ def test_get_for_models_partial_cache(self):
             FooWithUrl: ContentType.objects.get_for_model(FooWithUrl),
         })

+    def test_get_for_models_migrations(self):
+        state = ProjectState.from_apps(apps.get_app_config('contenttypes'))
+        ContentType = state.apps.get_model('contentypes', 'ContentType')
+        self.assertIs(ContentType.objects.get_for_models(ContentType), ContentType)
+
     def test_get_for_models_full_cache(self):
         # Full cache
         ContentType.objects.get_for_model(ContentType)
```

**Comment by felixxm** [comment]
@HMaker Do you have time to keep working on this?

**Comment by felixxm** [comment]
Closing due to inactivity.
