### PR TITLE
Refs #36326 -- Fixed QuerySet.raw() crash on models with CompositePrimaryKey on Oracle.

### PR DESCRIPTION
**Pull request by felixxm**
Virtual `CompositePrimaryKey` fields should be ignored.

Regression in 1831f7733d3ef03d1ca7fac3e8d9f4c5e3e3375e.

Check out [logs](https://djangoci.com/job/django-oracle/database=oracle19,label=oracle,python=python3.13/lastCompletedBuild/testReport/composite_pk.tests/CompositePKTests/test_raw/).

### CODE REVIEW

**Comment by felixxm** [comment]
buildbot, test on oracle.

**Comment by nessita** [comment]
Since Jenkins logs disappear after a while, here's the traceback for posterity (database=oracle19,python=python3.13):
```
Error Message
'NoneType' object has no attribute 'lower'

Stacktrace
Traceback (most recent call last):
  File "/home/jenkins/workspace/django-oracle/database/oracle19/label/oracle/python/python3.13/tests/composite_pk/tests.py", line 163, in test_raw
    self.assertEqual(len(users), 1)
                     ~~~^^^^^^^
  File "/home/jenkins/workspace/django-oracle/database/oracle19/label/oracle/python/python3.13/django/db/models/query.py", line 2127, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "/home/jenkins/workspace/django-oracle/database/oracle19/label/oracle/python/python3.13/django/db/models/query.py", line 2122, in _fetch_all
    self._result_cache = list(self.iterator())
                         ~~~~^^^^^^^^^^^^^^^^^
  File "/home/jenkins/workspace/django-oracle/database/oracle19/label/oracle/python/python3.13/django/db/models/query.py", line 2149, in iterator
    yield from RawModelIterable(self)
  File "/home/jenkins/workspace/django-oracle/database/oracle19/label/oracle/python/python3.13/django/db/models/query.py", line 166, in __iter__
    ) = self.queryset.resolve_model_init_order()
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/jenkins/workspace/django-oracle/database/oracle19/label/oracle/python/python3.13/django/db/models/query.py", line 2080, in resolve_model_init_order
    f for f in self.model._meta.fields if converter(f.column) in self.columns
                                          ~~~~~~~~~^^^^^^^^^^
  File "/home/jenkins/workspace/django-oracle/database/oracle19/label/oracle/python/python3.13/django/db/backends/oracle/introspection.py", line 217, in identifier_converter
    return name.lower()
           ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'lower'
```

File: django/db/models/query.py [hunk 1]
```diff
@@ -2194,7 +2198,10 @@ def model_fields(self):
         converter = connections[self.db].introspection.identifier_converter
         model_fields = {}
         for field in self.model._meta.fields:
-            model_fields[converter(field.column)] = field
+            # Fields with None "column" should be ignored
+            # (e.g. CompositePrimaryKey).
+            if field.column:
+                model_fields[converter(field.column)] = field
```
Comment (nessita) [inline django/db/models/query.py:2204]: How do you feel about making this a comprehension dict?
```python
        return {
            converter(field.column): field
            for field in self.model._meta.fields
            # Fields with None "column" should be ignored
            # (e.g. CompositePrimaryKey).
            if field.column
        }
```

**Review by LilyFoote — APPROVED** [review]
The code change looks good to me.

I note that we're making the same change in two places though - does it make sense to make this more DRY? Or are they just coincidentally very similar?

File: django/db/models/query.py (hunk 1 above)
Comment (felixxm) [reply django/db/models/query.py]: Sure, if you think it's worth doing. Updated.

**Comment by felixxm** [comment]
@LilyFoote Thanks for the review :+1: 

> I note that we're making the same change in two places though - does it make sense to make this more DRY? Or are they just coincidentally very similar?

Actually, we can. I pushed a small adjustment to reuse `model_fields` in both cases.

**Review by LilyFoote — APPROVED** [review]

**Comment by felixxm** [comment]
buildbot, test on oracle.
