### PR TITLE
Fixed #31584 -- Fixed crash when chaining values()/values_list() after Exists() annotation and aggregation on Oracle.

### PR DESCRIPTION
**Pull request by felixxm**
Oracle requires the `EXISTS` expression to be wrapped in a `CASE WHEN` in the `GROUP BY` clause.

Regression in efa1908f662c19038a944129c81462485c4a9fe8.

ticket-31584

### CODE REVIEW

File: django/db/backends/base/features.py [hunk 1]
```diff
@@ -297,7 +297,8 @@ class BaseDatabaseFeatures:
     # field(s)?
     allows_multiple_constraints_on_same_fields = True
 
-    # Does the backend support boolean expressions in the SELECT clause?
+    # Does the backend support boolean expressions in SELECT and GROUP BY
+    # clauses?
```
Comment (felixxm) [inline django/db/backends/base/features.py:301]: I don't think it's worth to add a second flag for the `GROUP BY` clause. IMO we can reuse `supports_boolean_expr_in_select_clause`.

**Comment by felixxm** [comment]
buildbot, test on oracle.

**Comment by carltongibson** [comment]
_Ei!_ Come on Oracle... ⏱

**Comment by tomaszszymanski129** [comment]
After merging that results in
`AttributeError: 'ManyToOneRel' object has no attribute 'select_format'`
(django/db/models/sql/compiler.py line 142)
worked in 3.0.6
Will create a ticket with code to reproduce it and open an issue.
