### PR TITLE
Fixed #30542 -- Fixed crash of numerical aggregations with filter.

### PR DESCRIPTION
**Pull request by tienne-B**
Filters in annotations crashed when used with numerical-type aggregations (i.e. `Avg`, `StdDev`, and `Variance`). This was caused as the source expressions no not necessarily have an output_field (such as the filter field), which lead to an AttributeError: 'WhereNode' object has no attribute 'output_field'.

A regression test was also added for this case, and a release page for 2.2.3 was created.

Thanks to Chuan-Zheng Lee for the report.

Regression in c690afb and following two commits (each for different aggregations, e85afa5943695457c85e9bc1c5dc0d985004e303 and 6d4efa8e6a4cc7be4ba957dec71f6f63cd58700d)

### CODE REVIEW

File: tests/aggregation_regress/tests.py [hunk 1]
```diff
@@ -1507,6 +1507,13 @@ class DistinctAggregate(Aggregate):
             allow_distinct = True
         DistinctAggregate('foo', distinct=True)
 
+    def test_filter_on_numerical_aggregate(self):
+        # Regression #30542 - Float-valued aggregations and annotations with filters fail with AttributeError
```
Comment (pope1ni) [inline tests/aggregation_regress/tests.py]: This comment can be removed.

**Comment by tienne-B** [comment]
Created a new file for `docs/releases/2.2.3.txt` and removed the comment from the test.

**Comment by pope1ni** [comment]
Ticket [#30542](https://code.djangoproject.com/ticket/30542).

This is actually a regression in c690afb873cac8035a3cb3be7c597a5ff0e4b261 which affects `Avg()`. `StdDev()` and `Variance()` are affected by e85afa5943695457c85e9bc1c5dc0d985004e303 and 6d4efa8e6a4cc7be4ba957dec71f6f63cd58700d respectively.

**Comment by tienne-B** [comment]
So should I list the three? I chose 3d5e0f8 as it started the problematic code, even though it was not used anywhere (yet).

File: docs/releases/2.2.3.txt [hunk 2]
```diff
@@ -0,0 +1,13 @@
...
+
+*Release date TBA*
+
+Django 2.2.3 fixes several bugs in 2.2.2.
+
+Bugfixes
+========
+
+* Fixed a regression in Django 2.2.2 that prevented using filters on
+  certain query aggregations (:ticket:`30542`).
```
Comment (pope1ni) [inline docs/releases/2.2.3.txt]:
```
* Fixed a regression in Django 2.2 that prevented using filter clauses with
  certain aggregation functions (:ticket:`30542`).
```

**Comment by pope1ni** [comment]
> I chose [3d5e0f8](https://github.com/django/django/commit/3d5e0f8394688d40036e27cfcfac295e6fe62269) as it started the problematic code

I think https://github.com/django/django/commit/c690afb873cac8035a3cb3be7c597a5ff0e4b261 is more relevant.

File: docs/releases/2.2.3.txt (hunk 2 above)
Comment (tienne-B) [reply docs/releases/2.2.3.txt]: Thank you!

**Comment by tienne-B** [comment]
Changed the linked commit.

File: tests/aggregation_regress/tests.py [hunk 3]
```diff
@@ -1507,6 +1507,12 @@ class DistinctAggregate(Aggregate):
             allow_distinct = True
         DistinctAggregate('foo', distinct=True)
 
+    def test_filter_on_numerical_aggregate(self):
+        try:
+            list(Publisher.objects.annotate(good_length=Avg('book__pages', filter=Q(book__rating__gte=4.0))))
```
Comment (czlee) [inline tests/aggregation_regress/tests.py]: Just wondering, should this test also check the value of this result, and check both `.annotate()` and `.aggregate()`? I know it's not the specific regression we're fixing here, but if there doesn't already exist a regression test for numerical aggregates with filters, maybe it should go the whole way, similarly to other tests in this file?

**Comment by czlee** [comment]
Actually, I realized it can't possibly be true that there aren't existing regression tests for filtered aggregations, so I checked again and they're right here, courtesy of @orf from #8352: https://github.com/django/django/blob/2.2.2/tests/aggregation/test_filter_argument.py

They just didn't fire because they only check `Sum`, and this regression only affects `Avg`, `StdDev` and `Variance`. Thought I'd mention in case this informs how we want to update tests for this?

File: tests/aggregation_regress/tests.py (hunk 3 above)
Comment (felixxm) [reply tests/aggregation_regress/tests.py]: I would move test to the `tests/aggregation/test_filter_argument.py`, and yes, we should check the result instead of checking that exception is not raised, e.g.:
```python
def test_filtered_numerical_aggregates(self):
    for aggregate, expected_result in (
        (Avg, Approximate(66.7, 1)),
        (StdDev, Approximate(24.9, 1)),
        (Variance, Approximate(622.2, 1)),
   ):
       with self.subTest(aggregate=aggregate.__name__):
           agg = aggregate('age', filter=Q(name__startswith='test'))
           self.assertEqual(Author.objects.aggregate(age=agg)['age'], expected_result)
```

File: docs/releases/2.2.3.txt [hunk 4]
```diff
@@ -0,0 +1,13 @@
...
+
+*Release date TBA*
+
+Django 2.2.3 fixes several bugs in 2.2.2.
+
+Bugfixes
+========
+
+* Fixed a regression in Django 2.2 that prevented using filter clauses with
+  certain aggregation functions (:ticket:`30542`).
```
Comment (felixxm) [inline docs/releases/2.2.3.txt]:
```
* Fixed a regression in Django 2.2 where :class:`~django.db.models.Avg`,
  :class:`~django.db.models.StdDev`, and :class:`~django.db.models.Variance`
  crash with ``filter`` argument (:ticket:`30542`).
```

I added stub release notes for 2.2.3, please rebase your PR.

File: tests/aggregation_regress/tests.py (hunk 3 above)
Comment (tienne-B) [reply tests/aggregation_regress/tests.py]: Done, thank you @felixxm. @czlee: Don't think it would be necessary to check both `.annotate()` and `.aggregate()` as it is a test for the arithmetic operation, which would have the same behaviour in either case.

File: docs/releases/2.2.3.txt (hunk 4 above)
Comment (tienne-B) [reply docs/releases/2.2.3.txt]: Thanks!
